# yaml-language-server: https://json.schemastore.org/github-workflow.json

name: Deploy GitHub Pages

on:
  push:
    branches: ["master"]
  pull_request: {}
  workflow_dispatch:
defaults:
  run:
    shell: nu {0}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nushell
        uses: hustcer/setup-nu@v3

      - name: Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install build dependencies
        run: ./toolkit.nu install-deps

      - name: Build docs
        run: ./toolkit.nu build-wiki

      - name: Formatting
        uses: dprint/check@v2.2

      - name: Construct site
        run: ./toolkit.nu build-site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

