# yaml-language-server: https://json.schemastore.org/github-workflow.json

name: Deploy GitHub Pages

on:
  push:
    branches: ["master"]
  pull_request: {}
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: ./scripts/install.nu

      - name: Build docs
        working-directory: ./wiki
        run: mdbook build

      - name: Formatting
        uses: dprint/check@v2.2

      - name: Construct site
        run: ./scripts/build.nu

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

